# Final Project
Iris Qiu

## Topic 
**The analysis of the hazmat spills happened in California, especially the city of Richmond, CA, from 2010 to 6/1/2023.**

- **Dataset**: Hazmat Spill Reports - A dataset presents significant release or threatened release of a hazardous material in California from 2010 to 6/1/2023.
https://www.caloes.ca.gov/office-of-the-director/operations/response-operations/fire-rescue/hazardous-materials/spill-release-reporting/
(The dataset on the California Governor's Office of Emergency Services website linked above are separate by years, and I manually merge them into one Excel sheet. I have checked that all the columns headings are the same.)
- **Why I chose this topic**:
As I was assigned to report on Richmond this semester for J200, during several turns of interviews with the residents, I found out that the refinery has a great impact on their lives. Many residents said that they were born with asthma and have witnessed many flaring events. Also, according to the Richmond Environment and Asthma Community Health (REACH) Study done by
<a href="https://clear.ucsf.edu/reach#:~:text=Yet%2C%20what%20types%20of%20stress,CA%2C%20it%20approaches%2025%25.">UCSF</a>, the asthma rates in Richmond are nearly twice as high as in California. Thus, I would like to explore the trend of spills happened throught out the decade and its comparison between Richmond and other cities in California.

## Import Cleaned Data

In [1]:
import pandas as pd
import altair as alt
import geopandas as gpd
from keplergl import KeplerGl

In [2]:
hazmat_spills_clean = pd.read_csv(
    'hazmat_spills_clean.csv',
    dtype={
        'ZIP': object,
        'Control#' : object
    },
    parse_dates=['Notified Date', 'Incident Time']
)
hazmat_spills_clean

/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_47144/667418393.py:1: DtypeWarning: Columns (17,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  hazmat_spills_clean = pd.read_csv(

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,...,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address
0,'23-3596,2023-06-01 13:30:00,Green Clean Pressure Washing,petroleum,RP stated that a waste management truck experi...,3835 Kern Road,Chino,San Bernardino County,2023-05-31,1700,...,NaN,No,NaN,NaN,NaN,17,0,17:00,2023-05-31 17:00:00,"3835 Kern Road,Chino,San Bernardino County"
1,'23-3594,2023-06-01 13:15:00,CHP - Barstow,chemical,RP stated that a semi trucks breaks caught on ...,Lynwood Road Offramp I15,Lynwood,Los Angeles County,2023-05-31,2306,...,NaN,No,NaN,NaN,NaN,23,6,23:06,2023-05-31 23:06:00,"Lynwood Road Offramp I15,Lynwood,Los Angeles C..."
2,'23-3592,2023-06-01 12:07:00,California Northern Railroad,other,RP states: A bridge by MP 174.8 of the westval...,MP 174.8 of the westvalley sub division,Corning,Tehama County,2023-06-01,1715,...,NaN,No,NaN,NaN,NaN,17,15,17:15,2023-06-01 17:15:00,"MP 174.8 of the westvalley sub division,Cornin..."
3,'23-3590,2023-06-01 11:32:00,NRC,petroleum,"Per NRC: ""CALLER STATED THAT THREE 55 GALLON D...",Off of SR 118,Somis,Ventura County,2023-06-01,945,...,NaN,No,NaN,NaN,NaN,9,45,9:45,2023-06-01 09:45:00,"Off of SR 118,Somis,Ventura County"
4,'23-3589,2023-06-01 11:10:00,High Speed Rail,petroleum,RP stated that they were excavating soil and t...,H Street and Ventura Avenue,Fresno,Fresno County,2023-06-01,800,...,NaN,No,NaN,NaN,NaN,8,0,8:00,2023-06-01 08:00:00,"H Street and Ventura Avenue,Fresno,Fresno County"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99165,',2019-10-01 09:30:00,Sacramento Area Sewer District,sewage,RP advised that there was a blockage in the lo...,9801 Beachwood Dr,Orangevale,Sacramento County,2019-09-03,831,...,NaN,No,NaN,NaN,NaN,8,31,8:31,2019-09-03 08:31:00,"9801 Beachwood Dr,Orangevale,Sacramento County"
99166,',2019-10-12 01:35:00,UPRR,sewage,conductorsCaller states a locomotive was leaki...,"Roseville, CA to Sparks, NV",Roseville,Placer County,2019-10-11,2021,...,NaN,No,NaN,Unknown,NaN,20,21,20:21,2019-10-11 20:21:00,"Roseville, CA to Sparks, NV,Roseville,Placer C..."
99167,',2019-11-12 12:38:00,Whit O Briens,petroleum,RP states: While Piledriving a hydraulic hose ...,1374 Pier F Avenue,Long Beach,Los Angeles County,2019-11-12,1145,...,NaN,No,NaN,NaN,NaN,11,45,11:45,2019-11-12 11:45:00,"1374 Pier F Avenue,Long Beach,Los Angeles County"
99168,',2014-01-20 09:52:00,NRC,chemical,"Per NRC#1071643 ""DISPENSER #9 SPILLED ROUGHLY ...",1804 W 11TH ST,Tracy,San Joaquin County,2014-01-20,915,...,NaN,No,NaN,NaN,NaN,9,15,9:15,2014-01-20 09:15:00,"1804 W 11TH ST,Tracy,San Joaquin County"
99169,',2012-08-16 03:28:00,City of Newport Beach,other,RP states that a dredging company hit a sewer ...,1701 Bayside Dr,Newport Beach,Orange County,2012-08-15,2300,...,NaN,No,NaN,NaN,NaN,23,0,23:00,2012-08-15 23:00:00,"1701 Bayside Dr,Newport Beach,Orange County"

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
hazmat_spills_clean

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address
0,'23-3596,2023-06-01 13:30:00,Green Clean Pressure Washing,petroleum,RP stated that a waste management truck experi...,3835 Kern Road,Chino,San Bernardino County,2023-05-31,1700,Road,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,17,0,17:00,2023-05-31 17:00:00,"3835 Kern Road,Chino,San Bernardino County"
1,'23-3594,2023-06-01 13:15:00,CHP - Barstow,chemical,RP stated that a semi trucks breaks caught on ...,Lynwood Road Offramp I15,Lynwood,Los Angeles County,2023-05-31,2306,Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,23,6,23:06,2023-05-31 23:06:00,"Lynwood Road Offramp I15,Lynwood,Los Angeles C..."
2,'23-3592,2023-06-01 12:07:00,California Northern Railroad,other,RP states: A bridge by MP 174.8 of the westval...,MP 174.8 of the westvalley sub division,Corning,Tehama County,2023-06-01,1715,Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,17,15,17:15,2023-06-01 17:15:00,"MP 174.8 of the westvalley sub division,Cornin..."
3,'23-3590,2023-06-01 11:32:00,NRC,petroleum,"Per NRC: ""CALLER STATED THAT THREE 55 GALLON D...",Off of SR 118,Somis,Ventura County,2023-06-01,945,Waterways,Santa Clara River,Other,Dumping,No,NaN,No,NaN,No,NaN,NaN,NaN,9,45,9:45,2023-06-01 09:45:00,"Off of SR 118,Somis,Ventura County"
4,'23-3589,2023-06-01 11:10:00,High Speed Rail,petroleum,RP stated that they were excavating soil and t...,H Street and Ventura Avenue,Fresno,Fresno County,2023-06-01,800,Other,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,8,0,8:00,2023-06-01 08:00:00,"H Street and Ventura Avenue,Fresno,Fresno County"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99165,',2019-10-01 09:30:00,Sacramento Area Sewer District,sewage,RP advised that there was a blockage in the lo...,9801 Beachwood Dr,Orangevale,Sacramento County,2019-09-03,831,Residence,Storm Drain,Blockage,NaN,Unknown,NaN,No,NaN,No,NaN,NaN,NaN,8,31,8:31,2019-09-03 08:31:00,"9801 Beachwood Dr,Orangevale,Sacramento County"
99166,',2019-10-12 01:35:00,UPRR,sewage,conductorsCaller states a locomotive was leaki...,"Roseville, CA to Sparks, NV",Roseville,Placer County,2019-10-11,2021,Rail Road,Unknown,Mechanical,NaN,No,NaN,No,NaN,No,NaN,Unknown,NaN,20,21,20:21,2019-10-11 20:21:00,"Roseville, CA to Sparks, NV,Roseville,Placer C..."
99167,',2019-11-12 12:38:00,Whit O Briens,petroleum,RP states: While Piledriving a hydraulic hose ...,1374 Pier F Avenue,Long Beach,Los Angeles County,2019-11-12,1145,Waterways,Port of Longbeach,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,11,45,11:45,2019-11-12 11:45:00,"1374 Pier F Avenue,Long Beach,Los Angeles County"
99168,',2014-01-20 09:52:00,NRC,chemical,"Per NRC#1071643 ""DISPENSER #9 SPILLED ROUGHLY ...",1804 W 11TH ST,Tracy,San Joaquin County,2014-01-20,915,Merchant/Business,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,9,15,9:15,2014-01-20 09:15:00,"1804 W 11TH ST,Tracy,San Joaquin County"
99169,',2012-08-16 03:28:00,City of Newport Beach,other,RP states that a dredging company hit a sewer ...,1701 Bayside Dr,Newport Beach,Orange County,2012-08-15,2300,Ship/Harbor/Port,Newport Bay,Human Error,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,23,0,23:00,2012-08-15 23:00:00,"1701 Bayside Dr,Newport Beach,Orange County"

## View data

In [5]:
hazmat_spills_clean.head()

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address
0,'23-3596,2023-06-01 13:30:00,Green Clean Pressure Washing,petroleum,RP stated that a waste management truck experi...,3835 Kern Road,Chino,San Bernardino County,2023-05-31,1700,Road,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,17,0,17:00,2023-05-31 17:00:00,"3835 Kern Road,Chino,San Bernardino County"
1,'23-3594,2023-06-01 13:15:00,CHP - Barstow,chemical,RP stated that a semi trucks breaks caught on ...,Lynwood Road Offramp I15,Lynwood,Los Angeles County,2023-05-31,2306,Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,23,6,23:06,2023-05-31 23:06:00,"Lynwood Road Offramp I15,Lynwood,Los Angeles C..."
2,'23-3592,2023-06-01 12:07:00,California Northern Railroad,other,RP states: A bridge by MP 174.8 of the westval...,MP 174.8 of the westvalley sub division,Corning,Tehama County,2023-06-01,1715,Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,17,15,17:15,2023-06-01 17:15:00,"MP 174.8 of the westvalley sub division,Cornin..."
3,'23-3590,2023-06-01 11:32:00,NRC,petroleum,"Per NRC: ""CALLER STATED THAT THREE 55 GALLON D...",Off of SR 118,Somis,Ventura County,2023-06-01,945,Waterways,Santa Clara River,Other,Dumping,No,NaN,No,NaN,No,NaN,NaN,NaN,9,45,9:45,2023-06-01 09:45:00,"Off of SR 118,Somis,Ventura County"
4,'23-3589,2023-06-01 11:10:00,High Speed Rail,petroleum,RP stated that they were excavating soil and t...,H Street and Ventura Avenue,Fresno,Fresno County,2023-06-01,800,Other,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,8,0,8:00,2023-06-01 08:00:00,"H Street and Ventura Avenue,Fresno,Fresno County"

In [6]:
hazmat_spills_clean.tail()

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address
99165,',2019-10-01 09:30:00,Sacramento Area Sewer District,sewage,RP advised that there was a blockage in the lo...,9801 Beachwood Dr,Orangevale,Sacramento County,2019-09-03,831,Residence,Storm Drain,Blockage,NaN,Unknown,NaN,No,NaN,No,NaN,NaN,NaN,8,31,8:31,2019-09-03 08:31:00,"9801 Beachwood Dr,Orangevale,Sacramento County"
99166,',2019-10-12 01:35:00,UPRR,sewage,conductorsCaller states a locomotive was leaki...,"Roseville, CA to Sparks, NV",Roseville,Placer County,2019-10-11,2021,Rail Road,Unknown,Mechanical,NaN,No,NaN,No,NaN,No,NaN,Unknown,NaN,20,21,20:21,2019-10-11 20:21:00,"Roseville, CA to Sparks, NV,Roseville,Placer C..."
99167,',2019-11-12 12:38:00,Whit O Briens,petroleum,RP states: While Piledriving a hydraulic hose ...,1374 Pier F Avenue,Long Beach,Los Angeles County,2019-11-12,1145,Waterways,Port of Longbeach,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,11,45,11:45,2019-11-12 11:45:00,"1374 Pier F Avenue,Long Beach,Los Angeles County"
99168,',2014-01-20 09:52:00,NRC,chemical,"Per NRC#1071643 ""DISPENSER #9 SPILLED ROUGHLY ...",1804 W 11TH ST,Tracy,San Joaquin County,2014-01-20,915,Merchant/Business,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,9,15,9:15,2014-01-20 09:15:00,"1804 W 11TH ST,Tracy,San Joaquin County"
99169,',2012-08-16 03:28:00,City of Newport Beach,other,RP states that a dredging company hit a sewer ...,1701 Bayside Dr,Newport Beach,Orange County,2012-08-15,2300,Ship/Harbor/Port,Newport Bay,Human Error,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,23,0,23:00,2012-08-15 23:00:00,"1701 Bayside Dr,Newport Beach,Orange County"

Use df.info() to show the column names and what dtype the column is on the dataframe.

In [7]:
hazmat_spills_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99170 entries, 0 to 99169
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Control#                 99170 non-null  object
 1   Notified Date            99170 non-null  datetime64[ns]
 2   Agency                   99097 non-null  object
 3   1. Type                  99078 non-null  object
 4   Description              99170 non-null  object
 5   Location                 99170 non-null  object
 6   City                     99170 non-null  object
 7   County                   99170 non-null  object
 8   Incident Date            99170 non-null  object
 9   Time                     99170 non-null  int64
 10  Spill Site               99170 non-null  object
 11  Site                     35225 non-null  object
 12  CAUSE                    98647 non-null  object
 13  CAUSE_Other              13879 non-null  object
 14  Injuries YES/NO          99166 non-null  object
 15  Injuries #               4163 non-null   object
 16  Fatals YES/NO            99167 non-null  object
 17  Fatals #                 2950 non-null   object
 18  Evacs YES/NO             99167 non-null  object
 19  Evacs #                  2986 non-null   object
 20  Drinking Water Impacted  25473 non-null  object
 21  Known Impact             5655 non-null   object
 22  Hour                     99170 non-null  int64
 23  Minutes                  99170 non-null  int64
 24  Time_Cleaned             99170 non-null  object
 25  Incident Time            99170 non-null  datetime64[ns]
 26  address                  99170 non-null  object
dtypes: datetime64[ns](2), int64(3), object(22)
memory usage: 20.4+ MB

## Analysis of the time difference

In this section, I am going to look at the trend of spill cases in the decade and the trends of Richmond specifically.

### .min() and .max()

In [8]:
hazmat_spills_clean['Notified Date'].min()

Timestamp('2010-01-01 08:16:00')

In [9]:
hazmat_spills_clean['Notified Date'].max()

Timestamp('2023-06-01 13:30:00')

### Get the difference of the two date columns

In [10]:
hazmat_spills_clean['time_difference'] = hazmat_spills_clean['Notified Date'] - hazmat_spills_clean['Incident Time']

In [11]:
hazmat_spills_clean.head()

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address,time_difference
0,'23-3596,2023-06-01 13:30:00,Green Clean Pressure Washing,petroleum,RP stated that a waste management truck experi...,3835 Kern Road,Chino,San Bernardino County,2023-05-31,1700,Road,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,17,0,17:00,2023-05-31 17:00:00,"3835 Kern Road,Chino,San Bernardino County",0 days 20:30:00
1,'23-3594,2023-06-01 13:15:00,CHP - Barstow,chemical,RP stated that a semi trucks breaks caught on ...,Lynwood Road Offramp I15,Lynwood,Los Angeles County,2023-05-31,2306,Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,23,6,23:06,2023-05-31 23:06:00,"Lynwood Road Offramp I15,Lynwood,Los Angeles C...",0 days 14:09:00
2,'23-3592,2023-06-01 12:07:00,California Northern Railroad,other,RP states: A bridge by MP 174.8 of the westval...,MP 174.8 of the westvalley sub division,Corning,Tehama County,2023-06-01,1715,Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,17,15,17:15,2023-06-01 17:15:00,"MP 174.8 of the westvalley sub division,Cornin...",-1 days +18:52:00
3,'23-3590,2023-06-01 11:32:00,NRC,petroleum,"Per NRC: ""CALLER STATED THAT THREE 55 GALLON D...",Off of SR 118,Somis,Ventura County,2023-06-01,945,Waterways,Santa Clara River,Other,Dumping,No,NaN,No,NaN,No,NaN,NaN,NaN,9,45,9:45,2023-06-01 09:45:00,"Off of SR 118,Somis,Ventura County",0 days 01:47:00
4,'23-3589,2023-06-01 11:10:00,High Speed Rail,petroleum,RP stated that they were excavating soil and t...,H Street and Ventura Avenue,Fresno,Fresno County,2023-06-01,800,Other,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,8,0,8:00,2023-06-01 08:00:00,"H Street and Ventura Avenue,Fresno,Fresno County",0 days 03:10:00

In [12]:
hazmat_spills_clean.tail()

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address,time_difference
99165,',2019-10-01 09:30:00,Sacramento Area Sewer District,sewage,RP advised that there was a blockage in the lo...,9801 Beachwood Dr,Orangevale,Sacramento County,2019-09-03,831,Residence,Storm Drain,Blockage,NaN,Unknown,NaN,No,NaN,No,NaN,NaN,NaN,8,31,8:31,2019-09-03 08:31:00,"9801 Beachwood Dr,Orangevale,Sacramento County",28 days 00:59:00
99166,',2019-10-12 01:35:00,UPRR,sewage,conductorsCaller states a locomotive was leaki...,"Roseville, CA to Sparks, NV",Roseville,Placer County,2019-10-11,2021,Rail Road,Unknown,Mechanical,NaN,No,NaN,No,NaN,No,NaN,Unknown,NaN,20,21,20:21,2019-10-11 20:21:00,"Roseville, CA to Sparks, NV,Roseville,Placer C...",0 days 05:14:00
99167,',2019-11-12 12:38:00,Whit O Briens,petroleum,RP states: While Piledriving a hydraulic hose ...,1374 Pier F Avenue,Long Beach,Los Angeles County,2019-11-12,1145,Waterways,Port of Longbeach,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,11,45,11:45,2019-11-12 11:45:00,"1374 Pier F Avenue,Long Beach,Los Angeles County",0 days 00:53:00
99168,',2014-01-20 09:52:00,NRC,chemical,"Per NRC#1071643 ""DISPENSER #9 SPILLED ROUGHLY ...",1804 W 11TH ST,Tracy,San Joaquin County,2014-01-20,915,Merchant/Business,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,9,15,9:15,2014-01-20 09:15:00,"1804 W 11TH ST,Tracy,San Joaquin County",0 days 00:37:00
99169,',2012-08-16 03:28:00,City of Newport Beach,other,RP states that a dredging company hit a sewer ...,1701 Bayside Dr,Newport Beach,Orange County,2012-08-15,2300,Ship/Harbor/Port,Newport Bay,Human Error,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,23,0,23:00,2012-08-15 23:00:00,"1701 Bayside Dr,Newport Beach,Orange County",0 days 04:28:00

### Mean

In [13]:
hazmat_spills_clean['time_difference'].mean()

Timedelta('2 days 07:47:01.989311283')

### Median

In [14]:
hazmat_spills_clean['time_difference'].median()

Timedelta('0 days 01:37:00')

### Min.

In [15]:
hazmat_spills_clean['time_difference'].min()

Timedelta('-75970 days +01:48:00')

In [16]:
less_than_zero_days=hazmat_spills_clean[hazmat_spills_clean['time_difference'] < '0 days'].copy()

In [17]:
less_than_zero_days

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address,time_difference
2,'23-3592,2023-06-01 12:07:00,California Northern Railroad,other,RP states: A bridge by MP 174.8 of the westval...,MP 174.8 of the westvalley sub division,Corning,Tehama County,2023-06-01,1715,Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,17,15,17:15,2023-06-01 17:15:00,"MP 174.8 of the westvalley sub division,Cornin...",-1 days +18:52:00
32,'23-3554,2023-05-31 09:23:00,Green Clean Pressure Washing,petroleum,"Due to mechanical failure, a waste management ...",Springwoods Circle,Valle Vista,Riverside County,2023-05-31,1100,"Residence,Road",NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,11,0,11:00,2023-05-31 11:00:00,"Springwoods Circle,Valle Vista,Riverside County",-1 days +22:23:00
58,'23-3524,2023-05-30 10:16:00,Union Pacific Railroad,railroad,RP stated that a train with symbol: ILBMN30 st...,LAT: 32.8124715 LONG: -114.8337162,Winterhaven,Imperial County,2023-05-30,1126,Rail Road,NaN,Other,Trespasser Strike,No,NaN,Yes,1,No,NaN,NaN,NaN,11,26,11:26,2023-05-30 11:26:00,"LAT: 32.8124715 LONG: -114.8337162,Winterhaven...",-1 days +22:50:00
78,'23-3502,2023-05-28 01:48:00,UPRR,railroad derailment,RP states: 5 empty hopper rail cars ( GACX 636...,9391 Atkinson Street,Roseville,Placer County,2023-05-28,1250,Rail Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,50,12:50,2023-05-28 12:50:00,"9391 Atkinson Street,Roseville,Placer County",-1 days +12:58:00
79,'23-3501,2023-05-28 00:24:00,AERA Energy LLC,petroleum,RP states: A tank (S1547-1346-1/Permit number ...,LAT / 35.42914 N LON / 119.68819 W,McKittrick,Kern County,2023-05-28,2000,Oil Field,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,20,0,20:00,2023-05-28 20:00:00,"LAT / 35.42914 N LON / 119.68819 W,McKittrick...",-1 days +04:24:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98938,'10-7770,2010-12-22 11:51:00,NRC,unspecified,The individual is dumping used motor oil and a...,4196 24th Ave.,Sacramento,Sacramento County,2010-12-22,1200,Residence,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,0,12:00,2010-12-22 12:00:00,"4196 24th Ave. ,Sacramento,Sacramento County",-1 days +23:51:00
98941,'10-7773,2010-12-22 12:28:00,Ramona Municipal Water Dist,petroleum,This is a potential release due to the incomin...,260 Sawday St,Ramona,San Diego County,2010-12-22,1230,Treatment/Sewage Facility,NaN,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,30,12:30,2010-12-22 12:30:00,"260 Sawday St ,Ramona,San Diego County",-1 days +23:58:00
98972,'10-7804,2010-12-23 10:06:00,NRC,petroleum,Caller stated that there was a release of 25 g...,Willow Ave. and Bullard,Fresno,Fresno County,2010-12-23,1530,Road,NaN,Other,Fell off Truck,No,NaN,No,NaN,No,NaN,NaN,NaN,15,30,15:30,2010-12-23 15:30:00,"Willow Ave. and Bullard,Fresno,Fresno County",-1 days +18:36:00
98978,'10-7810,2010-12-23 11:05:00,NRC,sewage,CALLER STATES THAT THE COMPANY IS SAND BLASTIN...,TUJUNGA AVE & KENNETH,Burbank,Los Angeles County,2010-12-23,1349,Military Base,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,13,49,13:49,2010-12-23 13:49:00,"TUJUNGA AVE & KENNETH,Burbank,Los Angeles County",-1 days +21:16:00
99008,'10-7841,2010-12-24 13:56:00,Veeder Root,sewage,Caller states that the auto shut off valve fai...,2234 Otis Drive,Alameda,Alameda County,2010-12-24,1430,Service Station,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,14,30,14:30,2010-12-24 14:30:00,"2234 Otis Drive,Alameda,Alameda County",-1 days +23:26:00

In [18]:
less_than_zero_days['Incident Time'].min()

Timestamp('2010-01-02 09:30:00')

In [19]:
less_than_zero_days['Incident Time'].max()

Timestamp('2230-11-05 22:30:00')

The less than zero days might be caused by the wrong data entered!

### Max

In [20]:
hazmat_spills_clean['time_difference'].max()

Timedelta('43464 days 01:02:00')

In [21]:
hazmat_spills_clean[hazmat_spills_clean['time_difference'] >= '43464 days']

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address,time_difference
28071,'19-3861,2019-06-16 20:02:00,NRC,vapor,GASOLINE IS DISCHARGING FROM A FAULTY PUMP AT ...,775 CALIFORNIA 20 EAST,Upper Lake,Lake County,1900-06-16,1900,Service Station,DRAINAGE,Mechanical,NaN,No,NaN,No,NaN,No,NaN,Unknown,NaN,19,0,19:00,1900-06-16 19:00:00,"775 CALIFORNIA 20 EAST,Upper Lake,Lake County",43464 days 01:02:00

There might also be a typo in this row!

### Sort Data

In [22]:
hazmat_spills_clean.sort_values(by=['time_difference'], ascending=False)

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address,time_difference
28071,'19-3861,2019-06-16 20:02:00,NRC,vapor,GASOLINE IS DISCHARGING FROM A FAULTY PUMP AT ...,775 CALIFORNIA 20 EAST,Upper Lake,Lake County,1900-06-16,1900,Service Station,DRAINAGE,Mechanical,NaN,No,NaN,No,NaN,No,NaN,Unknown,NaN,19,0,19:00,1900-06-16 19:00:00,"775 CALIFORNIA 20 EAST,Upper Lake,Lake County",43464 days 01:02:00
10638,'21-7368,2021-12-23 15:01:00,Private Citizen,petroleum,RP state since 1950 Mendocino county started a...,2 mile West of Branscomb Rd,Laytonville,Mendocino County,1950-01-15,800,Other,"Wages Creek, Redwood Creek, leading into the P...",Other,Illegal dumping,Unknown,NaN,Unknown,NaN,No,NaN,NaN,NaN,8,0,8:00,1950-01-15 08:00:00,"2 mile West of Branscomb Rd ,Laytonville,Mendo...",26275 days 07:01:00
28458,'19-3436,2019-05-29 13:27:00,Concerned Citizen,petroleum,**Historical Report**RP states that in the 197...,612 South Flower,Los Angeles,Los Angeles County,1975-01-01,1200,Waterways,"Pacific Ocean, West Coast",Human Error,NaN,Unknown,Unknown Amount,No,NaN,No,NaN,Drinking Water,NaN,12,0,12:00,1975-01-01 12:00:00,"612 South Flower,Los Angeles,Los Angeles County",16219 days 01:27:00
51454,'16-4365,2016-07-19 12:02:00,NRC,chemical,*** HISTORIC REPORT *** According to NRC #1153...,56533 Highway 58 West,McKittrick,Kern County,1980-01-01,1200,Other,NaN,Other,Dumping,No,NaN,No,NaN,No,NaN,No,Unknown,12,0,12:00,1980-01-01 12:00:00,"56533 Highway 58 West,McKittrick,Kern County",13349 days 00:02:00
52348,'16-3366,2016-06-05 08:32:00,NRC,chemical,** HISTORICAL REPORT** Per the NRC Report # 11...,Lockheed Aircraft B-1 Plant Fabrication Dept,Burbank,Los Angeles County,1989-01-01,1200,"Industrial Plant,Merchant/Business",Storm Drain,Human Error,NaN,No,NaN,No,NaN,No,NaN,Unknown,Unknown,12,0,12:00,1989-01-01 12:00:00,"Lockheed Aircraft B-1 Plant Fabrication Dept,B...",10016 days 20:32:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59530,'15-4354,2015-07-29 09:45:00,NRC,railroad,Per the NRC Report: CALLER IS REPORTING OIL SE...,"Latitude: 34° 18' 32"" N, Longitude: 118° 41' 2...",Simi Valley,Ventura County,2105-07-22,1200,Other,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,0,12:00,2105-07-22 12:00:00,"Latitude: 34° 18' 32"" N, Longitude: 118° 41' 2...",-32866 days +21:45:00
45748,'17-2641,2017-04-06 15:14:00,Contra Costa Co Hazmat,petroleum,RP states that the substances were found by Cl...,High Street at Mitchell Creek,Clayton,Contra Costa County,2107-04-04,1819,Waterways,Mitchell Creek,Human Error,NaN,No,NaN,No,NaN,No,NaN,No,NaN,18,19,18:19,2107-04-04 18:19:00,"High Street at Mitchell Creek,Clayton,Contra C...",-32870 days +20:55:00
51536,'16-4276,2016-07-14 18:24:00,UPRR,chemical,Per the caller a train struck a bicylist at a ...,MP 14.25 of the Fresno Sub,Sacramento,Sacramento County,2106-07-14,1809,Rail Road,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,No,NaN,18,9,18:09,2106-07-14 18:09:00,"MP 14.25 of the Fresno Sub,Sacramento,Sacramen...",-32871 days +00:15:00
22832,'20-1222,2020-03-03 00:34:00,San Diego County Health Dept,other,Caller states that 3 abandonded 55 gallon drum...,573 Raleigh Ave,El Cajon,San Diego County,2205-03-03,2200,Merchant/Business,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,22,0,22:00,2205-03-03 22:00:00,"573 Raleigh Ave,El Cajon,San Diego County",-67570 days +02:34:00
4421,'22-6543,2022-11-06 00:18:00,NRC,railroad,THE CALLER DISCOVERED A VESSEL WITH AN INTERNA...,11 HARBOR WAY,Santa Barbara,Santa Barbara County,2230-11-05,2230,Ship/Harbor/Port,SANTA BARBARA HARBOR,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,22,30,22:30,2230-11-05 22:30:00,"11 HARBOR WAY,Santa Barbara,Santa Barbara County",-75970 days +01:48:00

### Count how many incidents per year

In [23]:
hazmat_spills_complete = hazmat_spills_clean.loc[
    (hazmat_spills_clean['Incident Time'] >= '2010-01-01') &
    (hazmat_spills_clean['Incident Time'] < '2023-01-01')
].reset_index(drop=True)

In [24]:
hazmat_spills_complete

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address,time_difference
0,'23-3396,2023-05-23 12:22:00,Private Citizen,other,***Historical Report*** RP states that suspect...,3885 North Madera Ave,Kerman,Fresno County,2022-12-15,1700,Residence,NaN,Human Error,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,17,0,17:00,2022-12-15 17:00:00,"3885 North Madera Ave,Kerman,Fresno County",158 days 19:22:00
1,'23-3025,2023-05-05 12:40:00,The Gill Corporation,chemical,**Historical Report** RP stated that there was...,4056 Easy Street,El Monte,Los Angeles County,2022-06-15,1420,Merchant/Business,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,14,20,14:20,2022-06-15 14:20:00,"4056 Easy Street,El Monte,Los Angeles County",323 days 22:20:00
2,'23-2910,2023-04-29 16:35:00,Private Citizen,sewage,Reporting Party states an active septic from a...,14057 Ettawa Springs Road,Middletown,Lake County,2022-11-01,1200,Residence,Big Canyon Creek,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,0,12:00,2022-11-01 12:00:00,"14057 Ettawa Springs Road,Middletown,Lake County",179 days 04:35:00
3,'23-2862,2023-04-27 09:16:00,Private Citizen,radiological,The X-ray machine at the listed location has b...,4920 Verdugo Way,Camarillo,Ventura County,2022-12-15,800,Merchant/Business,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,8,0,8:00,2022-12-15 08:00:00,"4920 Verdugo Way ,Camarillo,Ventura County",133 days 01:16:00
4,'23-2707,2023-04-19 10:29:00,Tesoro LA Refinery - Carson Operation,vapor,An emergency flaring resulted in exceeding the...,2350 East 223rd Street,Carson,Los Angeles County,2019-04-01,1000,Refinery,NaN,Other,Emergency Flaring,No,NaN,No,NaN,No,NaN,NaN,NaN,10,0,10:00,2019-04-01 10:00:00,"2350 East 223rd Street ,Carson,Los Angeles County",1479 days 00:29:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95807,',2019-10-01 09:30:00,Sacramento Area Sewer District,sewage,RP advised that there was a blockage in the lo...,9801 Beachwood Dr,Orangevale,Sacramento County,2019-09-03,831,Residence,Storm Drain,Blockage,NaN,Unknown,NaN,No,NaN,No,NaN,NaN,NaN,8,31,8:31,2019-09-03 08:31:00,"9801 Beachwood Dr,Orangevale,Sacramento County",28 days 00:59:00
95808,',2019-10-12 01:35:00,UPRR,sewage,conductorsCaller states a locomotive was leaki...,"Roseville, CA to Sparks, NV",Roseville,Placer County,2019-10-11,2021,Rail Road,Unknown,Mechanical,NaN,No,NaN,No,NaN,No,NaN,Unknown,NaN,20,21,20:21,2019-10-11 20:21:00,"Roseville, CA to Sparks, NV,Roseville,Placer C...",0 days 05:14:00
95809,',2019-11-12 12:38:00,Whit O Briens,petroleum,RP states: While Piledriving a hydraulic hose ...,1374 Pier F Avenue,Long Beach,Los Angeles County,2019-11-12,1145,Waterways,Port of Longbeach,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,11,45,11:45,2019-11-12 11:45:00,"1374 Pier F Avenue,Long Beach,Los Angeles County",0 days 00:53:00
95810,',2014-01-20 09:52:00,NRC,chemical,"Per NRC#1071643 ""DISPENSER #9 SPILLED ROUGHLY ...",1804 W 11TH ST,Tracy,San Joaquin County,2014-01-20,915,Merchant/Business,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,9,15,9:15,2014-01-20 09:15:00,"1804 W 11TH ST,Tracy,San Joaquin County",0 days 00:37:00
95811,',2012-08-16 03:28:00,City of Newport Beach,other,RP states that a dredging company hit a sewer ...,1701 Bayside Dr,Newport Beach,Orange County,2012-08-15,2300,Ship/Harbor/Port,Newport Bay,Human Error,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,23,0,23:00,2012-08-15 23:00:00,"1701 Bayside Dr,Newport Beach,Orange County",0 days 04:28:00

#### Use df.groupby() with datetimes

In [25]:
annual_cases = hazmat_spills_complete.groupby([pd.Grouper(key='Incident Time', axis=0, freq='A')]).count()

In [26]:
annual_cases

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,address,time_difference
Incident Time,,,,,,,,,,,,,,,,,,,,,,,,,,,
2010-12-31,7566,7566,7555,7565,7566,7566,7566,7566,7566,7566,7566,3112,7530,909,7565,213,7565,141,7565,118,1,0,7566,7566,7566,7566,7566
2011-12-31,7169,7169,7159,7168,7169,7169,7169,7169,7169,7169,7169,2718,7149,993,7169,220,7169,159,7169,138,0,0,7169,7169,7169,7169,7169
2012-12-31,7513,7513,7508,7511,7513,7513,7513,7513,7513,7513,7513,2847,7505,1086,7512,276,7512,202,7512,124,3,1,7513,7513,7513,7513,7513
2013-12-31,7432,7432,7432,7426,7432,7432,7432,7432,7432,7432,7432,2481,7419,967,7432,266,7432,195,7432,134,5,0,7432,7432,7432,7432,7432
2014-12-31,6877,6877,6871,6868,6877,6877,6877,6877,6877,6877,6877,2382,6863,983,6877,286,6877,207,6877,115,4,2,6877,6877,6877,6877,6877
2015-12-31,7139,7139,7134,7126,7139,7139,7139,7139,7139,7139,7139,2264,7122,1124,7139,321,7139,217,7139,141,21,10,7139,7139,7139,7139,7139
2016-12-31,7235,7235,7230,7231,7235,7235,7235,7235,7235,7235,7235,2373,7199,1291,7234,369,7234,244,7234,134,6396,1933,7235,7235,7235,7235,7235
2017-12-31,8388,8388,8384,8386,8388,8388,8388,8388,8388,8388,8388,3140,8333,1737,8388,347,8388,244,8388,289,7563,1946,8388,8388,8388,8388,8388
2018-12-31,8167,8167,8158,8158,8167,8167,8167,8167,8167,8167,8167,2502,8098,1101,8167,368,8167,235,8167,249,7137,1755,8167,8167,8167,8167,8167
2019-12-31,7678,7678,7675,7660,7678,7678,7678,7678,7678,7678,7678,2653,7615,1071,7678,340,7678,279,7678,350,1854,1,7678,7678,7678,7678,7678
2020-12-31,6577,6577,6575,6567,6577,6577,6577,6577,6577,6577,6577,2283,6529,659,6577,325,6577,226,6577,370,1113,0,6577,6577,6577,6577,6577
2021-12-31,6922,6922,6920,6921,6922,6922,6922,6922,6922,6922,6922,2583,6870,712,6922,331,6922,234,6922,366,1358,0,6922,6922,6922,6922,6922
2022-12-31,7149,7149,7142,7134,7149,7149,7149,7149,7149,7149,7149,2571,7090,612,7149,357,7149,267,7149,333,0,0,7149,7149,7149,7149,7149

In [27]:
annual_cases = annual_cases[['Control#']].reset_index()
annual_cases

   Incident Time  Control#
0     2010-12-31      7566
1     2011-12-31      7169
2     2012-12-31      7513
3     2013-12-31      7432
4     2014-12-31      6877
5     2015-12-31      7139
6     2016-12-31      7235
7     2017-12-31      8388
8     2018-12-31      8167
9     2019-12-31      7678
10    2020-12-31      6577
11    2021-12-31      6922
12    2022-12-31      7149

In [28]:
annual_cases.rename(columns={'Control#': 'cases'}, inplace=True)

In [29]:
annual_cases['year'] = annual_cases['Incident Time'].dt.year

In [30]:
annual_cases

   Incident Time  cases  year
0     2010-12-31   7566  2010
1     2011-12-31   7169  2011
2     2012-12-31   7513  2012
3     2013-12-31   7432  2013
4     2014-12-31   6877  2014
5     2015-12-31   7139  2015
6     2016-12-31   7235  2016
7     2017-12-31   8388  2017
8     2018-12-31   8167  2018
9     2019-12-31   7678  2019
10    2020-12-31   6577  2020
11    2021-12-31   6922  2021
12    2022-12-31   7149  2022

In [31]:
annual_cases = annual_cases[['year', 'cases']].copy()

In [32]:
annual_cases

    year  cases
0   2010   7566
1   2011   7169
2   2012   7513
3   2013   7432
4   2014   6877
5   2015   7139
6   2016   7235
7   2017   8388
8   2018   8167
9   2019   7678
10  2020   6577
11  2021   6922
12  2022   7149

In [33]:
annual_cases.sort_values(by=['cases'], ascending=False).reset_index(drop=True)

    year  cases
0   2017   8388
1   2018   8167
2   2019   7678
3   2010   7566
4   2012   7513
5   2013   7432
6   2016   7235
7   2011   7169
8   2022   7149
9   2015   7139
10  2021   6922
11  2014   6877
12  2020   6577

2017 has the most spill cases and 2020 has the least.

#### Visualize

In [34]:
alt.Chart(annual_cases).mark_bar().encode(
    x='year:O',
    y='cases'
).properties(
    title='California Spills: Number of cases by year'
)

alt.Chart(...)

The incidence of spills in California remained relatively stable over the past decade, with a notable peak in 2017 and a decline in 2020.

## Median time_difference by year and by agency

On Cal OES's website, there is no clear data directory, but the California Hazardous Materials Spill / Release Notification Guidance said that “All significant spills or threatened releases of hazardous materials, including oil and radioactive materials, must be immediately reported. Notification shall be made by telephone.” https://www.caloes.ca.gov/wp-content/uploads/Fire-Rescue/Documents/CalOES-Spill_Booklet_Feb2014_FINAL_BW_Acc.pdf

Thus, I am going to check the time difference between the government's notified time and the actual incident time.

### By year

In [35]:
median_time_difference = hazmat_spills_complete[
    ['Incident Time', 'time_difference']
].groupby([pd.Grouper(key='Incident Time', axis=0, freq='A') ]).median()

median_time_difference

              time_difference
Incident Time
2010-12-31    0 days 01:30:00
2011-12-31    0 days 01:35:00
2012-12-31    0 days 01:42:00
2013-12-31    0 days 01:42:00
2014-12-31    0 days 01:36:00
2015-12-31    0 days 01:39:00
2016-12-31    0 days 01:35:00
2017-12-31    0 days 01:29:00
2018-12-31    0 days 01:21:00
2019-12-31    0 days 01:39:00
2020-12-31    0 days 01:35:00
2021-12-31    0 days 01:48:00
2022-12-31    0 days 01:49:00

In [36]:
median_time_difference = median_time_difference.reset_index()
median_time_difference['year'] = median_time_difference['Incident Time'].dt.year

In [37]:
median_time_difference.columns = ['Incident Time', 'time_difference', 'year']

In [38]:
median_time_difference

   Incident Time time_difference  year
0     2010-12-31 0 days 01:30:00  2010
1     2011-12-31 0 days 01:35:00  2011
2     2012-12-31 0 days 01:42:00  2012
3     2013-12-31 0 days 01:42:00  2013
4     2014-12-31 0 days 01:36:00  2014
5     2015-12-31 0 days 01:39:00  2015
6     2016-12-31 0 days 01:35:00  2016
7     2017-12-31 0 days 01:29:00  2017
8     2018-12-31 0 days 01:21:00  2018
9     2019-12-31 0 days 01:39:00  2019
10    2020-12-31 0 days 01:35:00  2020
11    2021-12-31 0 days 01:48:00  2021
12    2022-12-31 0 days 01:49:00  2022

In [39]:
median_time_difference = median_time_difference[['year', 'time_difference']].copy()

In [40]:
median_time_difference

    year time_difference
0   2010 0 days 01:30:00
1   2011 0 days 01:35:00
2   2012 0 days 01:42:00
3   2013 0 days 01:42:00
4   2014 0 days 01:36:00
5   2015 0 days 01:39:00
6   2016 0 days 01:35:00
7   2017 0 days 01:29:00
8   2018 0 days 01:21:00
9   2019 0 days 01:39:00
10  2020 0 days 01:35:00
11  2021 0 days 01:48:00
12  2022 0 days 01:49:00

Since I encourtered the error of ValueError: Field "close_time" has type "timedelta64[ns]" which is not supported by Altair. Please convert to either a timestamp or a numerical value.

I need to convert `timedelta` to a different unit.

In [41]:
median_time_difference['time_difference_nanoseconds'] = median_time_difference['time_difference'].astype(int)
median_time_difference

    year time_difference  time_difference_nanoseconds
0   2010 0 days 01:30:00                5400000000000
1   2011 0 days 01:35:00                5700000000000
2   2012 0 days 01:42:00                6120000000000
3   2013 0 days 01:42:00                6120000000000
4   2014 0 days 01:36:00                5760000000000
5   2015 0 days 01:39:00                5940000000000
6   2016 0 days 01:35:00                5700000000000
7   2017 0 days 01:29:00                5340000000000
8   2018 0 days 01:21:00                4860000000000
9   2019 0 days 01:39:00                5940000000000
10  2020 0 days 01:35:00                5700000000000
11  2021 0 days 01:48:00                6480000000000
12  2022 0 days 01:49:00                6540000000000

In [42]:
alt.Chart(median_time_difference[['year', 'time_difference_nanoseconds']]).mark_bar().encode(
    x='year:O',
    y='time_difference_nanoseconds',
).properties(
    title='California Spill Release Report: Median reporting time'
)

alt.Chart(...)

In [43]:
alt.Chart(median_time_difference[['year', 'time_difference_nanoseconds']]).mark_bar().encode(
    x=alt.X('year:O', sort='-y'),
    y='time_difference_nanoseconds',
).properties(
    title='California Spill Release Report: Median reporting time'
)

alt.Chart(...)

### By agency

In [44]:
agency_time=hazmat_spills_complete[['Agency', 'Notified Date', 'Incident Time', 'time_difference']].copy()

In [45]:
agency_time

,Agency,Notified Date,Incident Time,time_difference
0,Private Citizen,2023-05-23 12:22:00,2022-12-15 17:00:00,158 days 19:22:00
1,The Gill Corporation,2023-05-05 12:40:00,2022-06-15 14:20:00,323 days 22:20:00
2,Private Citizen,2023-04-29 16:35:00,2022-11-01 12:00:00,179 days 04:35:00
3,Private Citizen,2023-04-27 09:16:00,2022-12-15 08:00:00,133 days 01:16:00
4,Tesoro LA Refinery - Carson Operation,2023-04-19 10:29:00,2019-04-01 10:00:00,1479 days 00:29:00
...,...,...,...,...
95807,Sacramento Area Sewer District,2019-10-01 09:30:00,2019-09-03 08:31:00,28 days 00:59:00
95808,UPRR,2019-10-12 01:35:00,2019-10-11 20:21:00,0 days 05:14:00
95809,Whit O Briens,2019-11-12 12:38:00,2019-11-12 11:45:00,0 days 00:53:00
95810,NRC,2014-01-20 09:52:00,2014-01-20 09:15:00,0 days 00:37:00
95811,City of Newport Beach,2012-08-16 03:28:00,2012-08-15 23:00:00,0 days 04:28:00

Since I would like to group the time difference by agency, I will first check out the number of unique agency just in case there are too many. As I checking this, I can also look at the number of cases by agencies.

#### Number of spills by agency

In [46]:
agency_time['Agency'].unique()

array(['Private Citizen', 'The Gill Corporation',
       'Tesoro LA Refinery - Carson Operation', ..., 'afdasdf', 'TEST ',
       'xxx'], dtype=object)

In [47]:
agency_time['Agency'].value_counts()

Agency
NRC                                 12581
UPRR                                 5866
PG&E                                 2780
ERTS                                 2755
Chevron                              1276
                                    ...
Castaic Resident                        1
CHP San Luis Obispo CC                  1
 A16992                                 1
Tuttle Click Chrysler Jeep Dodge        1
xxx                                     1
Name: count, Length: 20614, dtype: int64

In [48]:
agency=agency_time['Agency'].value_counts().to_frame()

In [49]:
agency.head(30)

                                count
Agency
NRC                             12581
UPRR                             5866
PG&E                             2780
ERTS                             2755
Chevron                          1276
Private Citizen                  1266
BNSF                             1236
CHP                               938
Southern California Edison        881
Southwest Gas                     725
Citizen                           679
NRC                               629
So Cal Edison                     621
Union Pacific Railroad            541
Veeder Root                       525
SoCal Gas                         521
SoCal Edison                      498
Hazmat One                        478
City of San Diego                 448
Union Pacific Railroad (UPRR)     389
Hazmat 1                          349
National Response Center (NRC)    308
Green Clean Pressure Washing      297
Waste Management                  295
Kinder Morgan                     291
So Cal Gas                        290
Ventura Foods                     265
San Diego Harbor Police           249
Sacramento Area Sewer District    248
Metrolink                         237

Since there are too many agencies and the listed agencies such as 'NRC' https://nrc.uscg.mil/ and 'ERTS' https://www.ertsonline.com/ are actually spills reporting agency that are responsible for reporting spills for certian companies, I am going to pick the five actual oil&gas companies with the most spill cases to see their time difference.

It also turns out from the above that many **freight railroad companies** (e.g., UPRR, BNSF ) account for a large portion of spills. Additionally, **Chevron** has ranked quite high in spills incident among all other companies.

In [50]:
agency=agency.reset_index()

In [51]:
agency

                                 Agency  count
0                                   NRC  12581
1                                  UPRR   5866
2                                  PG&E   2780
3                                  ERTS   2755
4                               Chevron   1276
...                                 ...    ...
20609                  Castaic Resident      1
20610            CHP San Luis Obispo CC      1
20611                            A16992      1
20612  Tuttle Click Chrysler Jeep Dodge      1
20613                               xxx      1

[20614 rows x 2 columns]

In [52]:
agency.head(25)

                            Agency  count
0                              NRC  12581
1                             UPRR   5866
2                             PG&E   2780
3                             ERTS   2755
4                          Chevron   1276
5                  Private Citizen   1266
6                             BNSF   1236
7                              CHP    938
8       Southern California Edison    881
9                    Southwest Gas    725
10                         Citizen    679
11                            NRC     629
12                   So Cal Edison    621
13          Union Pacific Railroad    541
14                     Veeder Root    525
15                       SoCal Gas    521
16                    SoCal Edison    498
17                      Hazmat One    478
18               City of San Diego    448
19   Union Pacific Railroad (UPRR)    389
20                        Hazmat 1    349
21  National Response Center (NRC)    308
22    Green Clean Pressure Washing    297
23                Waste Management    295
24                   Kinder Morgan    291

In [53]:
agency=agency.loc[[2, 4, 14, 15, 24]]

In [54]:
agency

           Agency  count
2            PG&E   2780
4         Chevron   1276
14    Veeder Root    525
15      SoCal Gas    521
24  Kinder Morgan    291

In [55]:
agency['Agency'] = agency['Agency'].astype(str)

In [56]:
alt.Chart(agency).mark_bar().encode(
    y='count',
    x=alt.X('Agency', sort='-y')
).properties(
    title='Number of spills by agency'
)

alt.Chart(...)

PG&E recorded the highest number of spill cases in the decade, followed by Chevron as the second-highest.

#### Median time difference by agency

In [57]:
median_time_difference_agency = agency_time.groupby('Agency')['time_difference'].median()
median_time_difference_agency

Agency
  City of Portola                          0 days 01:11:00
  DCOR                                     0 days 00:44:00
  LA County Public Works                   0 days 04:13:00
  LA Unified School District               0 days 06:31:00
  Oxnard FD                                0 days 00:57:00
                                                ...
private citizen                            1 days 20:56:00
sacramento county department of airpots    0 days 00:09:00
solve 1                                    0 days 02:05:00
xxx                                       23 days 23:25:00
xxxxx                                      0 days 00:25:00
Name: time_difference, Length: 20614, dtype: timedelta64[ns]

In [58]:
median_time_difference_agency=median_time_difference_agency.to_frame().reset_index()

In [59]:
median_time_difference_agency['Agency']=median_time_difference_agency['Agency'].astype(str)

In [60]:
median_time_difference_agency

                                        Agency  time_difference
0                            City of Portola    0 days 01:11:00
1                                         DCOR  0 days 00:44:00
2                       LA County Public Works  0 days 04:13:00
3                   LA Unified School District  0 days 06:31:00
4                                    Oxnard FD  0 days 00:57:00
...                                        ...              ...
20609                         private citizen   1 days 20:56:00
20610  sacramento county department of airpots  0 days 00:09:00
20611                                  solve 1  0 days 02:05:00
20612                                      xxx 23 days 23:25:00
20613                                    xxxxx  0 days 00:25:00

[20614 rows x 2 columns]

In [61]:
median_time_difference_agency=median_time_difference_agency[
    (median_time_difference_agency['Agency'] == 'PG&E')|(median_time_difference_agency['Agency'] == 'Chevron')| 
    (median_time_difference_agency['Agency'] == 'Veeder Root')|(median_time_difference_agency['Agency'] == 'SoCal Gas')| 
    (median_time_difference_agency['Agency'] == 'Kinder Morgan')]

In [62]:
median_time_difference_agency

              Agency time_difference
4576         Chevron 0 days 03:36:00
10360  Kinder Morgan 0 days 00:13:00
13493           PG&E 0 days 03:13:30
17372      SoCal Gas 0 days 01:57:00
19668    Veeder Root 0 days 00:29:00

In [63]:
median_time_difference_agency['time_difference_nanoseconds'] = median_time_difference_agency['time_difference'].astype(int)
median_time_difference_agency

/var/folders/s1/34kl6rwj7nx2q7mpwcv0yq1w0000gn/T/ipykernel_47144/3792262511.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  median_time_difference_agency['time_difference_nanoseconds'] = median_time_difference_agency['time_difference'].astype(int)

              Agency time_difference  time_difference_nanoseconds
4576         Chevron 0 days 03:36:00               12960000000000
10360  Kinder Morgan 0 days 00:13:00                 780000000000
13493           PG&E 0 days 03:13:30               11610000000000
17372      SoCal Gas 0 days 01:57:00                7020000000000
19668    Veeder Root 0 days 00:29:00                1740000000000

In [64]:
alt.Chart(median_time_difference_agency[['Agency', 'time_difference_nanoseconds']]).mark_bar().encode(
    x=alt.X('Agency', sort='-y'),
    y='time_difference_nanoseconds',
).properties(
    title='Median reporting time by Agency'
)

alt.Chart(...)

It is very interesting that Chevron has the longest reporting time.

## Analysis of the type

### View all the unique values of **Type**

In [65]:
hazmat_spills_clean['1. Type'].unique()

array(['petroleum', 'chemical', 'other', 'railroad derailment',
       'railroad', 'sewage', 'unspecified', 'vapor', 'chemical,vapor',
       'chemical,railroad', 'radiological',
       'petroleum,railroad derailment', 'petroleum,railroad',
       'chemical,petroleum', 'railroad,unspecified', 'chemical,sewage',
       'railroad,other', 'biomedical', 'petroleum,sewage',
       'vapor,unspecified', nan, 'vapor,chemical', 'railroad,vapor',
       'petroleum,vapor', 'railroad,sewage', 'petroleum,unspecified',
       'sewage,other', 'chemical,unspecified', 'petroleum,other',
       'chemical,other', 'sewage,unspecified', 'vapor,other',
       'railroad,railroad derailment',
       'petroleum,railroad,railroad derailment',
       'chemical,petroleum,other', 'sewage,vapor', 'biomedical,sewage',
       'chemical,petroleum,vapor', 'chemical,railroad,vapor',
       'biomedical,railroad', 'unspecified,vapor',
       'chemical,petroleum,unspecified', 'petroleum,chemical',
       'radiological,other', 'chemical,petroleum,sewage',
       'vapor,railroad', 'chemical,radiological', 'vapor,petroleum',
       'petroleum,railroad,vapor', ' cleanup was completed', 'unknown',
       'railroad,petroleum', 'other,vapor', 'unspecified,other',
       'storm drain', 'vapor,unspecified,other', 'petroleum,vapor,other',
       'no', 'other,petroleum'], dtype=object)

In [66]:
hazmat_spills_clean['1. Type'].value_counts()

1. Type
petroleum                                 47265
sewage                                    16249
chemical                                  10615
vapor                                      8561
railroad                                   6227
other                                      4858
unspecified                                2737
railroad derailment                        1261
petroleum,railroad                          258
radiological                                213
chemical,vapor                              166
chemical,petroleum                          101
chemical,railroad                            86
petroleum,vapor                              63
chemical,other                               50
railroad,vapor                               47
sewage,other                                 36
petroleum,other                              34
railroad,other                               27
biomedical                                   23
railroad,railroad derailment                 23
railroad,unspecified                         20
vapor,unspecified                            19
petroleum,unspecified                        18
petroleum,chemical                           16
vapor,other                                  15
vapor,chemical                               10
chemical,sewage                              10
chemical,unspecified                          9
petroleum,sewage                              7
vapor,petroleum                               6
chemical,petroleum,vapor                      5
railroad,sewage                               5
sewage,vapor                                  4
railroad,petroleum                            3
petroleum,railroad derailment                 3
chemical,petroleum,other                      2
chemical,railroad,vapor                       2
chemical,petroleum,unspecified                2
radiological,other                            2
vapor,railroad                                2
chemical,radiological                         2
petroleum,vapor,other                         1
vapor,unspecified,other                       1
storm drain                                   1
no                                            1
unspecified,other                             1
other,vapor                                   1
unknown                                       1
sewage,unspecified                            1
 cleanup was completed                        1
petroleum,railroad,vapor                      1
chemical,petroleum,sewage                     1
unspecified,vapor                             1
biomedical,railroad                           1
biomedical,sewage                             1
petroleum,railroad,railroad derailment        1
other,petroleum                               1
Name: count, dtype: int64

In [67]:
spills_type=hazmat_spills_clean['1. Type'].value_counts().to_frame()

In [68]:
spills_type=spills_type.reset_index()
spills_type

                                   1. Type  count
0                                petroleum  47265
1                                   sewage  16249
2                                 chemical  10615
3                                    vapor   8561
4                                 railroad   6227
5                                    other   4858
6                              unspecified   2737
7                      railroad derailment   1261
8                       petroleum,railroad    258
9                             radiological    213
10                          chemical,vapor    166
11                      chemical,petroleum    101
12                       chemical,railroad     86
13                         petroleum,vapor     63
14                          chemical,other     50
15                          railroad,vapor     47
16                            sewage,other     36
17                         petroleum,other     34
18                          railroad,other     27
19                              biomedical     23
20            railroad,railroad derailment     23
21                    railroad,unspecified     20
22                       vapor,unspecified     19
23                   petroleum,unspecified     18
24                      petroleum,chemical     16
25                             vapor,other     15
26                          vapor,chemical     10
27                         chemical,sewage     10
28                    chemical,unspecified      9
29                        petroleum,sewage      7
30                         vapor,petroleum      6
31                chemical,petroleum,vapor      5
32                         railroad,sewage      5
33                            sewage,vapor      4
34                      railroad,petroleum      3
35           petroleum,railroad derailment      3
36                chemical,petroleum,other      2
37                 chemical,railroad,vapor      2
38          chemical,petroleum,unspecified      2
39                      radiological,other      2
40                          vapor,railroad      2
41                   chemical,radiological      2
42                   petroleum,vapor,other      1
43                 vapor,unspecified,other      1
44                             storm drain      1
45                                      no      1
46                       unspecified,other      1
47                             other,vapor      1
48                                 unknown      1
49                      sewage,unspecified      1
50                   cleanup was completed      1
51                petroleum,railroad,vapor      1
52               chemical,petroleum,sewage      1
53                       unspecified,vapor      1
54                     biomedical,railroad      1
55                       biomedical,sewage      1
56  petroleum,railroad,railroad derailment      1
57                         other,petroleum      1

In [69]:
spills_type.columns  = ['type', 'cases']
spills_type

                                      type  cases
0                                petroleum  47265
1                                   sewage  16249
2                                 chemical  10615
3                                    vapor   8561
4                                 railroad   6227
5                                    other   4858
6                              unspecified   2737
7                      railroad derailment   1261
8                       petroleum,railroad    258
9                             radiological    213
10                          chemical,vapor    166
11                      chemical,petroleum    101
12                       chemical,railroad     86
13                         petroleum,vapor     63
14                          chemical,other     50
15                          railroad,vapor     47
16                            sewage,other     36
17                         petroleum,other     34
18                          railroad,other     27
19                              biomedical     23
20            railroad,railroad derailment     23
21                    railroad,unspecified     20
22                       vapor,unspecified     19
23                   petroleum,unspecified     18
24                      petroleum,chemical     16
25                             vapor,other     15
26                          vapor,chemical     10
27                         chemical,sewage     10
28                    chemical,unspecified      9
29                        petroleum,sewage      7
30                         vapor,petroleum      6
31                chemical,petroleum,vapor      5
32                         railroad,sewage      5
33                            sewage,vapor      4
34                      railroad,petroleum      3
35           petroleum,railroad derailment      3
36                chemical,petroleum,other      2
37                 chemical,railroad,vapor      2
38          chemical,petroleum,unspecified      2
39                      radiological,other      2
40                          vapor,railroad      2
41                   chemical,radiological      2
42                   petroleum,vapor,other      1
43                 vapor,unspecified,other      1
44                             storm drain      1
45                                      no      1
46                       unspecified,other      1
47                             other,vapor      1
48                                 unknown      1
49                      sewage,unspecified      1
50                   cleanup was completed      1
51                petroleum,railroad,vapor      1
52               chemical,petroleum,sewage      1
53                       unspecified,vapor      1
54                     biomedical,railroad      1
55                       biomedical,sewage      1
56  petroleum,railroad,railroad derailment      1
57                         other,petroleum      1

There are too many rows, I will just look at the top five types

In [70]:
spills_type=spills_type.iloc[[0,1,2,3,4]]
spills_type

        type  cases
0  petroleum  47265
1     sewage  16249
2   chemical  10615
3      vapor   8561
4   railroad   6227

### Visualizing the type vs. cases

In [71]:
alt.Chart(spills_type).mark_bar().encode(
    y='cases',
    x=alt.X('type', sort='-y')
).properties(
    title='Types of spills from 2010 to 2023'
)

alt.Chart(...)

Petroleum is the most common material in spill cases.

## Analysis of the Cause

In [72]:
hazmat_spills_clean['CAUSE']

0         Mechanical
1            Unknown
2            Unknown
3              Other
4            Unknown
            ...
99165       Blockage
99166     Mechanical
99167     Mechanical
99168     Mechanical
99169    Human Error
Name: CAUSE, Length: 99170, dtype: object

In [73]:
hazmat_spills_clean['CAUSE'].value_counts()

CAUSE
Unknown        29670
Mechanical     17687
Human Error    15389
Other          13730
Blockage        9646
Collision       8669
Broken Pipe     1898
Overflow        1581
Rail             377
Name: count, dtype: int64

In [74]:
spills_cause=hazmat_spills_clean['CAUSE'].value_counts().to_frame()

In [75]:
spills_cause.reset_index()

         CAUSE  count
0      Unknown  29670
1   Mechanical  17687
2  Human Error  15389
3        Other  13730
4     Blockage   9646
5    Collision   8669
6  Broken Pipe   1898
7     Overflow   1581
8         Rail    377

It is scary to know that the most common cause is "unknown" and human error has caused more than 15,000 cases.

## Analysis of Chevron Refinery

#### Filter out incidents caused by Chevron

In [76]:
chevron_spills=hazmat_spills_complete[hazmat_spills_complete['Agency'].str.contains('Chevron').fillna(False)].copy()

In [77]:
chevron_spills

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address,time_difference
46,'23-0062,2023-01-03 15:43:00,Chevron,petroleum,Due to a customer overfueling their gas tank t...,14526 Baseline Rd,Fontana,San Bernardino County,2022-01-03,1426,Merchant/Business,Storm Drain,Human Error,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,14,26,14:26,2022-01-03 14:26:00,"14526 Baseline Rd,Fontana,San Bernardino County",365 days 01:17:00
190,'22-7613,2022-12-30 13:03:00,Chevron,petroleum,RP States: A flow line has a pinhole leak caus...,Cymric Oil Field (Well Location Number 8ZLW27C),Unincorporated county area Kern Basin Area,Kern County,2022-12-30,1250,Oil Field,Unnamed Waterway,Broken Pipe,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,50,12:50,2022-12-30 12:50:00,Cymric Oil Field (Well Location Number 8ZLW27C...,0 days 00:13:00
193,'22-7610,2022-12-30 12:27:00,Chevron,petroleum,Reporting party states a customer was fueling ...,2905 West Benjamin Holt Drive,Stockton,San Joaquin County,2022-12-30,1145,Merchant/Business,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,11,45,11:45,2022-12-30 11:45:00,"2905 West Benjamin Holt Drive,Stockton,San Joa...",0 days 00:42:00
203,'22-7598,2022-12-29 21:32:00,Chevron,petroleum,"Customer filling their vehicle, went inside th...",4295 Clayton Road,Concord,Contra Costa County,2022-12-29,2010,Service Station,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,20,10,20:10,2022-12-29 20:10:00,"4295 Clayton Road,Concord,Contra Costa County",0 days 01:22:00
216,'22-7585,2022-12-29 11:32:00,Chevron,petroleum,Reporting party states there was a mechanical ...,"35.36624 N - 119.67870 W, 100 ft SW of the coo...",McKittrick,Kern County,2022-12-29,1110,Merchant/Business,Dry stream bed,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,11,10,11:10,2022-12-29 11:10:00,"35.36624 N - 119.67870 W, 100 ft SW of the coo...",0 days 00:22:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95414,'10-7598,2010-12-18 13:59:00,Chevron,unspecified,Caller states that during fueling a vehicle th...,10 Union Ave,Bakersfield,Kern County,2010-12-18,1000,Service Station,Storm Drain,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,10,0,10:00,2010-12-18 10:00:00,"10 Union Ave,Bakersfield,Kern County",0 days 03:59:00
95448,'10-7633,2010-12-19 13:35:00,Chevron,petroleum,A earth containment structure overflow due to ...,36W Township: 29S Range: 21E,McKittrick,Kern County,2010-12-19,1000,Oil Field,NaN,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,10,0,10:00,2010-12-19 10:00:00,"36W Township: 29S Range: 21E,McKittrick,Kern...",0 days 03:35:00
95508,'10-7694,2010-12-21 08:13:00,Chevron Pipeline,petroleum,A pump suffered a packing failure causing the ...,LAT: 35' 383 N LONG: 119.742 W,Unincorporated county.,Kern County,2010-12-21,738,Other,NaN,Mechanical,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,7,38,7:38,2010-12-21 07:38:00,"LAT: 35' 383 N LONG: 119.742 W,Unincorpora...",0 days 00:35:00
95688,'10-7879,2010-12-27 10:53:00,Chevron El Segundo Refinery 800030,petroleum,Notification of a possible SOX exceeding limit...,324 West El Segundo Blvd,El Segundo,Los Angeles County,2010-12-27,1041,Refinery,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,10,41,10:41,2010-12-27 10:41:00,"324 West El Segundo Blvd,El Segundo,Los Angele...",0 days 00:12:00
95705,'10-7897,2010-12-28 01:48:00,Chevron Richmond Refinery,petroleum,Caller states the release was caused by an ups...,"841 Chevron Way, Chevron Richmond Refinery",Richmond,Contra Costa County,2010-12-28,110,Refinery,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,1,10,1:10,2010-12-28 01:10:00,"841 Chevron Way, Chevron Richmond Refinery,Ric...",0 days 00:38:00

#### Get annual cases

In [78]:
annual_cases_chevron = chevron_spills.groupby([pd.Grouper(key='Incident Time', axis=0, freq='A')]).count()

In [79]:
annual_cases_chevron

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,address,time_difference
Incident Time,,,,,,,,,,,,,,,,,,,,,,,,,,,
2010-12-31,58,58,58,58,58,58,58,58,58,58,58,9,58,8,58,0,58,0,58,0,0,0,58,58,58,58,58
2011-12-31,76,76,76,76,76,76,76,76,76,76,76,4,75,9,76,1,76,1,76,0,0,0,76,76,76,76,76
2012-12-31,98,98,98,97,98,98,98,98,98,98,98,7,98,7,98,0,98,0,98,1,0,0,98,98,98,98,98
2013-12-31,70,70,70,70,70,70,70,70,70,70,70,4,70,2,70,0,70,0,70,0,0,0,70,70,70,70,70
2014-12-31,86,86,86,86,86,86,86,86,86,86,86,5,86,12,86,0,86,0,86,1,0,0,86,86,86,86,86
2015-12-31,115,115,115,115,115,115,115,115,115,115,115,7,114,8,115,1,115,0,115,0,0,0,115,115,115,115,115
2016-12-31,172,172,172,170,172,172,172,172,172,172,172,24,172,30,172,0,172,0,172,0,151,8,172,172,172,172,172
2017-12-31,189,189,189,189,189,189,189,189,189,189,189,46,189,19,189,0,189,0,189,0,171,6,189,189,189,189,189
2018-12-31,237,237,237,236,237,237,237,237,237,237,237,30,237,16,237,1,237,0,237,0,191,6,237,237,237,237,237
2019-12-31,236,236,236,236,236,236,236,236,236,236,236,23,236,18,236,0,236,0,236,0,10,0,236,236,236,236,236
2020-12-31,126,126,126,125,126,126,126,126,126,126,126,17,126,6,126,0,126,0,126,2,2,0,126,126,126,126,126
2021-12-31,116,116,116,116,116,116,116,116,116,116,116,15,116,14,116,0,116,0,116,0,3,0,116,116,116,116,116
2022-12-31,176,176,176,176,176,176,176,176,176,176,176,13,175,8,176,0,176,0,176,0,0,0,176,176,176,176,176

In [80]:
annual_cases_chevron = annual_cases_chevron[['Control#']].reset_index()
annual_cases_chevron

   Incident Time  Control#
0     2010-12-31        58
1     2011-12-31        76
2     2012-12-31        98
3     2013-12-31        70
4     2014-12-31        86
5     2015-12-31       115
6     2016-12-31       172
7     2017-12-31       189
8     2018-12-31       237
9     2019-12-31       236
10    2020-12-31       126
11    2021-12-31       116
12    2022-12-31       176

In [81]:
annual_cases_chevron.rename(columns={'Control#': 'cases'}, inplace=True)
annual_cases_chevron

   Incident Time  cases
0     2010-12-31     58
1     2011-12-31     76
2     2012-12-31     98
3     2013-12-31     70
4     2014-12-31     86
5     2015-12-31    115
6     2016-12-31    172
7     2017-12-31    189
8     2018-12-31    237
9     2019-12-31    236
10    2020-12-31    126
11    2021-12-31    116
12    2022-12-31    176

In [82]:
annual_cases_chevron['year'] = annual_cases_chevron['Incident Time'].dt.year
annual_cases_chevron

   Incident Time  cases  year
0     2010-12-31     58  2010
1     2011-12-31     76  2011
2     2012-12-31     98  2012
3     2013-12-31     70  2013
4     2014-12-31     86  2014
5     2015-12-31    115  2015
6     2016-12-31    172  2016
7     2017-12-31    189  2017
8     2018-12-31    237  2018
9     2019-12-31    236  2019
10    2020-12-31    126  2020
11    2021-12-31    116  2021
12    2022-12-31    176  2022

In [83]:
annual_cases_chevron = annual_cases_chevron[['year', 'cases']].copy()

In [84]:
annual_cases_chevron

    year  cases
0   2010     58
1   2011     76
2   2012     98
3   2013     70
4   2014     86
5   2015    115
6   2016    172
7   2017    189
8   2018    237
9   2019    236
10  2020    126
11  2021    116
12  2022    176

In [85]:
annual_cases_chevron['cases'].mean()

135.0

#### Visualize

In [86]:
alt.Chart(annual_cases_chevron).mark_bar().encode(
    x=alt.X('year:O'),
    y=alt.Y('cases'),
).properties(
    title={
        'text': 'California Spills Release Report',
        'subtitle' : ['Number of cases caused by Chevron by year']
    }
)

alt.Chart(...)

Spill incidents caused by Chevron rose from 2016, peaking in 2018 and 2019, followed by a subsequent decline, and then increased in 2022 again. It caused 135 incidents on average per year in California.

## Analysis of the spills happened in the city of Richmond

### Count how many incidents per year

In [87]:
richmond_spills=hazmat_spills_complete[hazmat_spills_complete['City'].str.contains('Richmond').fillna(False)].copy()

In [88]:
richmond_spills

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,Incident Time,address,time_difference
138,'22-7667,2022-12-31 12:46:00,City of Richmond,sewage,RP stated that due to the storm a manhole is o...,Marina Way South and Cutting Blvd,Richmond,Contra Costa County,2022-12-31,1215,Road,SF Bay/ Storm Drain,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,15,12:15,2022-12-31 12:15:00,"Marina Way South and Cutting Blvd,Richmond,Con...",0 days 00:31:00
140,'22-7665,2022-12-31 12:39:00,City of Richmond,sewage,RP stated that due to the storm a manhole is o...,Pearson Avenue and Marina Way south,Richmond,Contra Costa County,2022-12-31,1215,Road,Storm Drain / San Francisco Bay,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,15,12:15,2022-12-31 12:15:00,"Pearson Avenue and Marina Way south,Richmond,C...",0 days 00:24:00
141,'22-7664,2022-12-31 12:39:00,City of Richmond,sewage,RP stated that due to the storm a manhole is o...,4700 Hartnet Avenue,Richmond,Contra Costa County,2022-12-31,1215,Road,Storm Drain / San Francisco Bay,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,12,15,12:15,2022-12-31 12:15:00,"4700 Hartnet Avenue ,Richmond,Contra Costa County",0 days 00:24:00
142,'22-7663,2022-12-31 12:39:00,City of Richmond,petroleum,RP stated that due to the storm a manhole is o...,Neeker Ave and Marina Way South,Richmond,Contra Costa County,2022-12-31,1050,Road,Storm Drain / San Francisco Bay,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,10,50,10:50,2022-12-31 10:50:00,"Neeker Ave and Marina Way South,Richmond,Contr...",0 days 01:49:00
143,'22-7662,2022-12-31 12:39:00,City of Richmond,sewage,RP stated that due to the storm a manhole is o...,Harbor Way South and Cutting Blvd,Richmond,Contra Costa County,2022-12-31,1050,Road,Storm Drain / San Francisco Bay,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,10,50,10:50,2022-12-31 10:50:00,"Harbor Way South and Cutting Blvd,Richmond,Con...",0 days 01:49:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95675,'10-7866,2010-12-26 15:02:00,NRC,sewage,"Per NRC report #963124 ""Area residents have re...","1340 Marina Way South Slip D-141A, D-Dock",Richmond,Contra Costa County,2010-12-26,1400,Ship/Harbor/Port,San Francisco Bay,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,14,0,14:00,2010-12-26 14:00:00,"1340 Marina Way South Slip D-141A, D-Dock ,Ric...",0 days 01:02:00
95705,'10-7897,2010-12-28 01:48:00,Chevron Richmond Refinery,petroleum,Caller states the release was caused by an ups...,"841 Chevron Way, Chevron Richmond Refinery",Richmond,Contra Costa County,2010-12-28,110,Refinery,NaN,Unknown,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,1,10,1:10,2010-12-28 01:10:00,"841 Chevron Way, Chevron Richmond Refinery,Ric...",0 days 00:38:00
95731,'10-7924,2010-12-28 21:14:00,City of Richmond,sewage,RP states that a constructed overflow weir is ...,860 harbour Way South,Richmond,Contra Costa County,2010-12-28,2050,Treatment/Sewage Facility,Santa Fe Channel,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,20,50,20:50,2010-12-28 20:50:00,"860 harbour Way South,Richmond,Contra Costa Co...",0 days 00:24:00
95735,'10-7928,2010-12-28 22:34:00,East Bay MUD,petroleum,Release due to storm surge from wet weather fa...,2755 Isaabel St (Isabel Facility),Richmond,Contra Costa County,2010-12-28,2222,Other,San Francisco Bay,Overflow,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,22,22,22:22,2010-12-28 22:22:00,"2755 Isaabel St (Isabel Facility),Richmond,Con...",0 days 00:12:00
95752,'10-7949,2010-12-29 10:31:00,Richmond Municipal Sewer District,petroleum,A blockage in the main line forced the sewage ...,3410 Barrett Ave.,Richmond,Contra Costa County,2010-12-29,945,Road,NaN,Blockage,NaN,No,NaN,No,NaN,No,NaN,NaN,NaN,9,45,9:45,2010-12-29 09:45:00,"3410 Barrett Ave. ,Richmond,Contra Costa County",0 days 00:46:00

There are at least in total of 1012 spills happened in Richmond from 2010 to 2022

#### Use df.groupby() with datetimes

In [89]:
annual_cases_richmond = richmond_spills.groupby([pd.Grouper(key='Incident Time', axis=0, freq='A')]).count()

In [90]:
annual_cases_richmond

,Control#,Notified Date,Agency,1. Type,Description,Location,City,County,Incident Date,Time,Spill Site,Site,CAUSE,CAUSE_Other,Injuries YES/NO,Injuries #,Fatals YES/NO,Fatals #,Evacs YES/NO,Evacs #,Drinking Water Impacted,Known Impact,Hour,Minutes,Time_Cleaned,address,time_difference
Incident Time,,,,,,,,,,,,,,,,,,,,,,,,,,,
2010-12-31,104,104,104,104,104,104,104,104,104,104,104,60,104,23,104,0,104,1,104,1,0,0,104,104,104,104,104
2011-12-31,88,88,88,88,88,88,88,88,88,88,88,61,88,24,88,1,88,2,88,1,0,0,88,88,88,88,88
2012-12-31,99,99,99,99,99,99,99,99,99,99,99,72,99,27,99,0,99,2,99,2,0,0,99,99,99,99,99
2013-12-31,50,50,50,50,50,50,50,50,50,50,50,29,50,5,50,3,50,1,50,2,0,0,50,50,50,50,50
2014-12-31,66,66,66,66,66,66,66,66,66,66,66,33,66,6,66,2,66,4,66,1,0,0,66,66,66,66,66
2015-12-31,57,57,57,57,57,57,57,57,57,57,57,27,57,8,57,1,57,4,57,0,0,0,57,57,57,57,57
2016-12-31,95,95,95,95,95,95,95,95,95,95,95,51,95,29,95,4,95,6,95,0,85,37,95,95,95,95,95
2017-12-31,106,106,106,106,106,106,106,106,106,106,106,62,106,28,106,5,106,5,106,0,97,38,106,106,106,106,106
2018-12-31,56,56,56,56,56,56,56,56,56,56,56,22,56,7,56,9,56,3,56,0,50,20,56,56,56,56,56
2019-12-31,85,85,85,85,85,85,85,85,85,85,85,38,84,16,85,3,85,6,85,1,20,0,85,85,85,85,85
2020-12-31,58,58,58,58,58,58,58,58,58,58,58,20,57,4,58,1,58,5,58,1,10,0,58,58,58,58,58
2021-12-31,71,71,71,71,71,71,71,71,71,71,71,35,71,20,71,3,71,1,71,1,21,0,71,71,71,71,71
2022-12-31,77,77,77,77,77,77,77,77,77,77,77,32,76,10,77,3,77,3,77,1,0,0,77,77,77,77,77

In [91]:
annual_cases_richmond = annual_cases_richmond[['Control#']].reset_index()
annual_cases_richmond

   Incident Time  Control#
0     2010-12-31       104
1     2011-12-31        88
2     2012-12-31        99
3     2013-12-31        50
4     2014-12-31        66
5     2015-12-31        57
6     2016-12-31        95
7     2017-12-31       106
8     2018-12-31        56
9     2019-12-31        85
10    2020-12-31        58
11    2021-12-31        71
12    2022-12-31        77

In [92]:
annual_cases_richmond.rename(columns={'Control#': 'cases'}, inplace=True)

In [93]:
annual_cases_richmond

   Incident Time  cases
0     2010-12-31    104
1     2011-12-31     88
2     2012-12-31     99
3     2013-12-31     50
4     2014-12-31     66
5     2015-12-31     57
6     2016-12-31     95
7     2017-12-31    106
8     2018-12-31     56
9     2019-12-31     85
10    2020-12-31     58
11    2021-12-31     71
12    2022-12-31     77

In [94]:
annual_cases_richmond['year']=annual_cases_richmond['Incident Time'].dt.year
annual_cases_richmond

   Incident Time  cases  year
0     2010-12-31    104  2010
1     2011-12-31     88  2011
2     2012-12-31     99  2012
3     2013-12-31     50  2013
4     2014-12-31     66  2014
5     2015-12-31     57  2015
6     2016-12-31     95  2016
7     2017-12-31    106  2017
8     2018-12-31     56  2018
9     2019-12-31     85  2019
10    2020-12-31     58  2020
11    2021-12-31     71  2021
12    2022-12-31     77  2022

In [95]:
annual_cases_richmond = annual_cases_richmond[['year', 'cases']].copy()

In [96]:
annual_cases_richmond

    year  cases
0   2010    104
1   2011     88
2   2012     99
3   2013     50
4   2014     66
5   2015     57
6   2016     95
7   2017    106
8   2018     56
9   2019     85
10  2020     58
11  2021     71
12  2022     77

In [97]:
annual_cases_richmond.sort_values(by=['cases'], ascending=False).reset_index(drop=True)

    year  cases
0   2017    106
1   2010    104
2   2012     99
3   2016     95
4   2011     88
5   2019     85
6   2022     77
7   2021     71
8   2014     66
9   2020     58
10  2015     57
11  2018     56
12  2013     50

In [98]:
annual_cases_richmond['cases'].mean()

77.84615384615384

- Richmond has the highest number of spills in 2017
- Year 2012 ranked the third with spill incidents. This year was also when the big flaring event caused by Chevron Refinery happened in Richmond that was still a fresh memory in many Richmond residents' mind. After 2012, The number of spills decreased a lot until 2016.
- The number of spills has been increased gradually from 2020 to 2022
- Richmond averaged 77 spills per year.

#### Visualize

In [99]:
alt.Chart(annual_cases_richmond).mark_bar().encode(
    x='year:O',
    y='cases'
).properties(
    title='Number of cases by year in Richmond'
)

alt.Chart(...)

### The comparison between Richmond and other cities

In [100]:
hazmat_spills_clean['City'].nunique()

1986

In [101]:
hazmat_spills_clean['City'].value_counts()

City
San Diego              5222
Los Angeles            2492
Long Beach             2054
Sacramento             2047
Bakersfield            1616
                       ...
La Selva Beach            1
Bear Valley Springs       1
Rio Del Mar               1
TRONA                     1
Miramonte                 1
Name: count, Length: 1986, dtype: int64

In [102]:
city=hazmat_spills_clean['City'].value_counts().to_frame().reset_index()

In [103]:
city.head(30)

                          City  count
0                    San Diego   5222
1                  Los Angeles   2492
2                   Long Beach   2054
3                   Sacramento   2047
4                  Bakersfield   1616
5                      Oakland   1553
6                     Stockton   1431
7                  Bloomington   1368
8   Unincorporated county area   1316
9               San Bernardino   1299
10               San Francisco   1114
11                    San Jose   1099
12                    Richmond   1068
13                      Fresno    946
14                     Ontario    848
15                   Roseville    792
16                      Oxnard    790
17                   Riverside    758
18               Santa Barbara    687
19                     Fontana    674
20                     Barstow    652
21                  Santa Rosa    603
22                  Wilmington    571
23            Santa Fe Springs    565
24                   Elk Grove    561
25                      Carson    537
26                     Alameda    515
27                   San Pedro    506
28                 Victorville    447
29            South Lake Tahoe    444

Richmond is ranked the 12th in California for the number of spill cases. San Diego has the highest number of spills in California.

### Mapping

In [104]:
richmond = pd.read_csv('address_richmond_geocoded.csv', dtype={'Zip': object})

In [105]:
richmond_gdf = gpd.GeoDataFrame(
    richmond, 
    geometry=gpd.points_from_xy(
        richmond['Longitude'], 
        richmond['Latitude']
    ),
)

In [106]:
richmond_gdf.tail()

,address,Latitude,Longitude,Accuracy Score,Accuracy Type,City,State,County,Zip,ACS Economics/Median household income/Total/Value,ACS Economics/Median household income/Total/Margin of error,ACS Demographics/Median age/Total/Value,ACS Demographics/Median age/Total/Margin of error,ACS Demographics/Race and ethnicity/Not Hispanic or Latino: White alone/Percentage,ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Black or African American alone/Percentage,ACS Demographics/Race and ethnicity/Not Hispanic or Latino: American Indian and Alaska Native alone/Percentage,ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Asian alone/Percentage,ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Native Hawaiian and Other Pacific Islander alone/Percentage,geometry
828,"1306 Channel Blvd,Richmond,Contra Costa County",37.911078,-122.327023,0.67,street_center,Richmond,CA,Contra Costa County,94804.0,105945.0,10039.0,43.9,10.4,0.501,0.164,0.0,0.310,0.000,POINT (-122.32702 37.91108)
829,"1340 Marina Way South Slip D-141A, D-Dock ,Ric...",37.917326,-122.355774,1.00,range_interpolation,Richmond,CA,Contra Costa County,94804.0,107880.0,52395.0,39.9,3.9,0.336,0.414,0.0,0.132,0.017,POINT (-122.35577 37.91733)
830,"860 harbour Way South,Richmond,Contra Costa Co...",37.920138,-122.359448,1.00,rooftop,Richmond,CA,Contra Costa County,94804.0,107880.0,52395.0,39.9,3.9,0.336,0.414,0.0,0.132,0.017,POINT (-122.35945 37.92014)
831,"2755 Isaabel St (Isabel Facility),Richmond,Con...",37.897055,-122.321880,1.00,range_interpolation,Richmond,CA,Contra Costa County,94804.0,105945.0,10039.0,43.9,10.4,0.501,0.164,0.0,0.310,0.000,POINT (-122.32188 37.89706)
832,"3410 Barrett Ave. ,Richmond,Contra Costa County",37.936604,-122.336033,0.95,rooftop,Richmond,CA,Contra Costa County,94805.0,88125.0,22284.0,41.7,6.8,0.277,0.159,0.0,0.345,0.000,POINT (-122.33603 37.93660)

In [107]:
config = {'version': 'v1',
 'config': {'visState': {'filters': [],
   'layers': [{'id': 'bthis',
     'type': 'heatmap',
     'config': {'dataId': 'richmond_spills',
      'label': 'Point',
      'color': [248, 149, 112],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat': 'Latitude', 'lng': 'Longitude'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'colorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#FFC300',
         '#F1920E',
         '#E3611C',
         '#C70039',
         '#900C3F',
         '#5A1846'],
        'reversed': True},
       'radius': 10},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'weightField': None, 'weightScale': 'linear'}},
    {'id': 'kqjh8eg',
     'type': 'geojson',
     'config': {'dataId': 'richmond_spills',
      'label': 'richmond_spills',
      'color': [130, 154, 227],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'geojson': 'geometry'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'strokeOpacity': 0.8,
       'thickness': 0.5,
       'strokeColor': None,
       'colorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'strokeColorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radius': 10,
       'sizeRange': [0, 10],
       'radiusRange': [0, 50],
       'heightRange': [0, 500],
       'elevationScale': 5,
       'enableElevationZoomFactor': True,
       'stroked': False,
       'filled': True,
       'enable3d': False,
       'wireframe': False},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': None,
      'colorScale': 'quantile',
      'strokeColorField': None,
      'strokeColorScale': 'quantile',
      'sizeField': None,
      'sizeScale': 'linear',
      'heightField': None,
      'heightScale': 'linear',
      'radiusField': None,
      'radiusScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'richmond_spills': [{'name': 'address',
        'format': None},
       {'name': 'Latitude', 'format': None},
       {'name': 'Longitude', 'format': None},
       {'name': 'ACS Economics/Median household income/Total/Value',
        'format': None},
       {'name': 'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: White alone/Percentage',
        'format': None},
       {'name': 'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Asian alone/Percentage',
        'format': None},
       {'name': 'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Black or African American alone/Percentage',
        'format': None},
       {'name': 'Accuracy Score', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 37.94229226155522,
   'longitude': -122.37907630628847,
   'pitch': 0,
   'zoom': 11.132723092760799,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'threeDBuildingColor': [9.665468314072013,
    17.18305478057247,
    31.1442867897876],
   'mapStyles': {}}}}

In [108]:
kepler_map = KeplerGl(height=800)

kepler_map.config = config 
kepler_map.add_data(
    data=richmond_gdf, name='richmond_spills'
)

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

/Users/qiu/Library/jupyterlab-desktop/jlab_server/lib/python3.8/site-packages/jupyter_client/session.py:719: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)

In [109]:
kepler_map

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [], 'layers': [{'id': 'bthis', 'type': 'h…

The map shows most of the spills happened in West South Richmond, but not so many happened in the areas uphills in Richmond.

When I reopened this notebook, sometimes the map did not run successfully, you may need to restart the kernal to see the map.

In [110]:
kepler_map.config

{'version': 'v1',
 'config': {'visState': {'filters': [],
   'layers': [{'id': 'bthis',
     'type': 'heatmap',
     'config': {'dataId': 'richmond_spills',
      'label': 'Point',
      'color': [248, 149, 112],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat': 'Latitude', 'lng': 'Longitude'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'colorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#FFC300',
         '#F1920E',
         '#E3611C',
         '#C70039',
         '#900C3F',
         '#5A1846'],
        'reversed': True},
       'radius': 10},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'weightField': None, 'weightScale': 'linear'}},
    {'id': 'kqjh8eg',
     'type': 'geojson',
     'config': {'dataId': 'richmond_spills',
      'label': 'richmond_spills',
      'color': [130, 154, 227],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'geojson': 'geometry'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'strokeOpacity': 0.8,
       'thickness': 0.5,
       'strokeColor': None,
       'colorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'strokeColorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radius': 10,
       'sizeRange': [0, 10],
       'radiusRange': [0, 50],
       'heightRange': [0, 500],
       'elevationScale': 5,
       'enableElevationZoomFactor': True,
       'stroked': False,
       'filled': True,
       'enable3d': False,
       'wireframe': False},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': None,
      'colorScale': 'quantile',
      'strokeColorField': None,
      'strokeColorScale': 'quantile',
      'sizeField': None,
      'sizeScale': 'linear',
      'heightField': None,
      'heightScale': 'linear',
      'radiusField': None,
      'radiusScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'richmond_spills': [{'name': 'address',
        'format': None},
       {'name': 'Latitude', 'format': None},
       {'name': 'Longitude', 'format': None},
       {'name': 'ACS Economics/Median household income/Total/Value',
        'format': None},
       {'name': 'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: White alone/Percentage',
        'format': None},
       {'name': 'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Asian alone/Percentage',
        'format': None},
       {'name': 'ACS Demographics/Race and ethnicity/Not Hispanic or Latino: Black or African American alone/Percentage',
        'format': None},
       {'name': 'Accuracy Score', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 37.94229226155522,
   'longitude': -122.37907630628847,
   'pitch': 0,
   'zoom': 11.132723092760799,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'threeDBuildingColor': [9.665468314072013,
    17.18305478057247,
    31.1442867897876],
   'mapStyles': {}}}}

## Summary of interesting findings from the analysis

- From 2010 to 2022, 2017 has the most spill cases and 2020 has the least.
- The incidence of spills in California remained relatively stable over the past decade, with a notable peak in 2017 and a decline in 2020.
- PG&E recorded the highest number of spill cases in the decade, followed by Chevron as the second-highest.
- Chevron recorded the longest median time for reporting the spill incident to the government.
- Petroleum is the most common material in spill cases.
- The most common cause is "unknown" and human error has caused more than 15,000 cases, which might indicate that there is a need for awareness and more incident prevention. 
- Spill incidents caused by Chevron rose from 2016, peaking in 2018 and 2019, followed by a subsequent decline, and then increased in 2022 again. It caused 135 incidents on average per year in California.
- Richmond averaged 77 spills per year. It has the highest number of spills in 2017. 2012 ranked the third with spill incidents. This year was also when the big flaring event caused by Chevron Refinery happened in Richmond that was still a fresh memory in many Richmond residents' mind. After 2012, The number of spills decreased a lot until 2016. It also increased gradually from 2020 to 2022
- Richmond is ranked the 12th in California for the number of spill cases. San Diego has the highest number of spills in California. 
- Most of the spills happened in West South Richmond.